version: '3.3'

services:
  webapp:
    build: ./webapp
    ports:
      - 2345:80
    depends_on: [backend]
    security_opt:
      - apparmor:unconfined
  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app
    ports:
      - 2001:80
    depends_on: [database]
    security_opt:
      - apparmor:unconfined
  database:
    image: postgres
    restart: always
    ports:
      - 3001:5432
    security_opt:
      - apparmor:unconfined